### ISSUE TITLE
Stat_Events.md page has an error

### ISSUE THREAD

**Issue by johnsturgeon** [BakkesModWiki/BakkesModWiki.github.io#8]
On the stat_events.md page, the struct for `StatEventParams` is:
```c++
// structure of a stat event
struct StatEventParams {
    // always primary player
    uintptr_t PRI;
    // wrapper for the stat event
    uintptr_t StatEvent;
};
```
But the handler code pulls a receiver out of the struct:
```c++
void ClassName::onStatEvent(void* params) {
    StatEventParams* pStruct = (StatEventParams*)params;
    PriWrapper receiver = PriWrapper(pStruct->Receiver);
    StatEventWrapper statEvent = StatEventWrapper(pStruct->StatEvent);
}
```

**Comment by johnsturgeon** [comment]
I would fix it, but I'm really not sure what the fix is.  Add a receiver to the struct?  Or remove it from the `onStatEvent` handler.

**Comment by ubelhj** [comment]
Good catch! Definitely a typo in the code. The PRI there is the primary player, as `Function TAGame.GFxHUD_TA.HandleStatEvent` only happens for the primary player
